/**
 * 文件作用：维护“用户指定直出”的人工岗位画像种子数据。
 * 依赖边界：仅提供纯数据常量，供脚本入库与接口触发复用。
 */

import type { ManualJobPortraitRecord } from "@career/contracts/types";

export type ManualJobPortraitSeedInput = Omit<ManualJobPortraitRecord, "created_at" | "updated_at">;

export const MANUAL_JOB_PORTRAITS_SEED: ManualJobPortraitSeedInput[] = [
  {
    job_name: "技术支持工程师",
    category: "support",
    skills: {
      level: 3,
      weight: 0.22,
      description: "掌握系统环境与网络基础，能够完成故障定位和远程支持",
    },
    certification: { level: 2, weight: 0.06, description: "具备软考或网络基础认证可加分" },
    innovation: { level: 2, weight: 0.12, description: "可沉淀知识库并优化工单流程" },
    learning: { level: 4, weight: 0.16, description: "能快速学习新产品与新问题场景" },
    stress: { level: 4, weight: 0.16, description: "可承受高峰并发工单和紧急故障压力" },
    communication: { level: 5, weight: 0.18, description: "擅长客户沟通与跨团队协作推进问题闭环" },
    experience: { level: 3, weight: 0.1, description: "有企业级技术支持经历优先" },
  },
  {
    job_name: "实施工程师",
    category: "implementation",
    skills: { level: 4, weight: 0.24, description: "具备部署上线、环境配置与数据库排障能力" },
    certification: { level: 2, weight: 0.05, description: "项目管理相关证书可加分" },
    innovation: { level: 3, weight: 0.12, description: "可结合客户场景优化交付流程" },
    learning: { level: 4, weight: 0.15, description: "快速掌握行业业务与系统逻辑" },
    stress: { level: 4, weight: 0.16, description: "项目节点集中时可稳定交付" },
    communication: {
      level: 5,
      weight: 0.18,
      description: "能够高质量完成需求澄清、培训与验收沟通",
    },
    experience: { level: 3, weight: 0.1, description: "有中大型项目实施经验优先" },
  },
  {
    job_name: "测试工程师",
    category: "qa",
    skills: { level: 4, weight: 0.26, description: "掌握功能、接口、回归测试与缺陷管理流程" },
    certification: { level: 2, weight: 0.05, description: "ISTQB 或软考测试方向可加分" },
    innovation: { level: 3, weight: 0.12, description: "可推动自动化测试与质量度量改进" },
    learning: { level: 4, weight: 0.15, description: "持续学习自动化框架与质量工程方法" },
    stress: { level: 4, weight: 0.16, description: "发布窗口内可高效保障回归质量" },
    communication: { level: 4, weight: 0.14, description: "与研发、产品协作推进缺陷闭环" },
    experience: { level: 3, weight: 0.12, description: "有完整项目测试周期经验优先" },
  },
  {
    job_name: "Java",
    category: "software",
    skills: { level: 5, weight: 0.28, description: "精通 Java 开发、Spring 生态与数据库设计" },
    certification: { level: 2, weight: 0.05, description: "Java/云厂商相关认证可加分" },
    innovation: { level: 4, weight: 0.14, description: "可参与高并发场景和架构优化" },
    learning: { level: 4, weight: 0.15, description: "持续学习中间件与云原生技术" },
    stress: { level: 3, weight: 0.12, description: "在交付周期内保持稳定研发节奏" },
    communication: { level: 3, weight: 0.12, description: "可与上下游团队高效协作联调" },
    experience: { level: 4, weight: 0.14, description: "有企业级后端项目经验优先" },
  },
  {
    job_name: "软件测试",
    category: "qa",
    skills: { level: 4, weight: 0.25, description: "掌握功能、接口、基础性能测试与数据校验" },
    certification: { level: 2, weight: 0.05, description: "软件评测方向证书可加分" },
    innovation: { level: 3, weight: 0.12, description: "可推动测试工具化与流程标准化" },
    learning: { level: 4, weight: 0.15, description: "可持续学习自动化脚本与质量体系" },
    stress: { level: 4, weight: 0.16, description: "上线前高压阶段仍能保证交付质量" },
    communication: { level: 4, weight: 0.14, description: "可与研发协作复现并定位问题" },
    experience: { level: 3, weight: 0.13, description: "有项目测试经验优先" },
  },
  {
    job_name: "C/C++",
    category: "software",
    skills: { level: 5, weight: 0.3, description: "精通 C/C++、算法与 Linux 系统级开发" },
    certification: { level: 1, weight: 0.04, description: "无强制认证，项目与竞赛经历更重要" },
    innovation: { level: 4, weight: 0.14, description: "可参与底层性能优化与架构迭代" },
    learning: { level: 4, weight: 0.14, description: "持续提升操作系统和编译工具链能力" },
    stress: { level: 3, weight: 0.12, description: "复杂问题定位场景下保持稳定输出" },
    communication: { level: 3, weight: 0.1, description: "可与多端协作推进接口与性能联调" },
    experience: { level: 4, weight: 0.16, description: "有高性能或底层系统开发经验优先" },
  },
  {
    job_name: "前端开发",
    category: "software",
    skills: { level: 5, weight: 0.28, description: "掌握 Vue/React、TypeScript 与前端工程化体系" },
    certification: { level: 1, weight: 0.04, description: "无强制认证，项目作品和代码质量更关键" },
    innovation: { level: 4, weight: 0.15, description: "可推动组件复用与性能体验优化" },
    learning: { level: 5, weight: 0.16, description: "可快速跟进前端生态变化与新框架能力" },
    stress: { level: 3, weight: 0.12, description: "在频繁迭代中稳定完成开发交付" },
    communication: { level: 4, weight: 0.13, description: "可与设计、后端高效协作完成联调" },
    experience: { level: 3, weight: 0.12, description: "有中大型前端项目经验优先" },
  },
  {
    job_name: "硬件测试",
    category: "hardware_qa",
    skills: { level: 4, weight: 0.26, description: "掌握硬件功能、稳定性测试与常见仪器使用" },
    certification: { level: 1, weight: 0.04, description: "无强制认证，电子基础和实操能力优先" },
    innovation: { level: 3, weight: 0.12, description: "可优化硬件测试方案与测试工装" },
    learning: { level: 4, weight: 0.14, description: "持续学习新平台测试方法与可靠性标准" },
    stress: { level: 3, weight: 0.14, description: "产线和交付节奏下保持测试质量稳定" },
    communication: { level: 3, weight: 0.12, description: "与硬件、嵌入式团队协作定位问题" },
    experience: { level: 4, weight: 0.18, description: "有硬件验证或可靠性测试经验优先" },
  },
  {
    job_name: "产品专员/助理",
    category: "product",
    skills: { level: 3, weight: 0.22, description: "具备需求分析、原型表达与文档输出能力" },
    certification: { level: 2, weight: 0.05, description: "产品管理相关证书可加分" },
    innovation: { level: 4, weight: 0.15, description: "可提出面向用户价值的功能优化方案" },
    learning: { level: 4, weight: 0.15, description: "持续跟进行业趋势与竞品变化" },
    stress: { level: 3, weight: 0.13, description: "可在需求变更与迭代节奏下稳定推进" },
    communication: { level: 5, weight: 0.18, description: "具备高频跨团队沟通与推进能力" },
    experience: { level: 2, weight: 0.12, description: "有产品实习或项目经历优先" },
  },
  {
    job_name: "网络销售",
    category: "network",
    skills: {
      level: 3,
      weight: 0.2,
      description: "理解网络产品基础，具备线上售前沟通与方案说明能力",
    },
    certification: { level: 1, weight: 0.04, description: "无强制认证，行业知识可作为加分项" },
    innovation: { level: 3, weight: 0.14, description: "可优化获客路径与线上转化流程" },
    learning: { level: 4, weight: 0.16, description: "快速学习产品与行业场景并转化为销售话术" },
    stress: { level: 4, weight: 0.18, description: "目标导向强，需承受业绩压力" },
    communication: { level: 5, weight: 0.18, description: "高频客户沟通，要求表达清晰且有说服力" },
    experience: { level: 2, weight: 0.1, description: "有 ToB 或互联网销售实习经验优先" },
  },
];
