/**
 * 文件作用：维护“用户指定直出”的人工岗位画像种子数据。
 * 依赖边界：仅提供纯数据常量，供脚本入库与接口触发复用。
 */

import type { ManualJobPortraitRecord } from "@career/contracts/types";

export type ManualJobPortraitSeedInput = Omit<ManualJobPortraitRecord, "created_at" | "updated_at">;

export const MANUAL_JOB_PORTRAITS_SEED: ManualJobPortraitSeedInput[] = [
  {
    job_name: "Java开发工程师",
    category: "software",
    skills: { level: 4, weight: 0.22, description: "掌握核心语法与代码优化，具备独立模块开发能力" },
    certification: { level: 4, weight: 0.1, description: "技术转管理建议补充PMP等证书" },
    innovation: { level: 4, weight: 0.14, description: "可在架构与实现层面持续优化" },
    learning: { level: 4, weight: 0.14, description: "能够持续学习新技术并适应变化" },
    stress: { level: 4, weight: 0.1, description: "可应对交付周期压力" },
    communication: { level: 3, weight: 0.15, description: "具备基础跨团队沟通协作能力" },
    experience: { level: 4, weight: 0.15, description: "理解项目交付周期与研发协作流程" },
  },
  {
    job_name: "前端开发工程师",
    category: "software",
    skills: { level: 4, weight: 0.22, description: "熟悉前端框架与页面交互开发，具备工程化能力" },
    certification: { level: 3, weight: 0.1, description: "相关专业基础要求中等" },
    innovation: { level: 4, weight: 0.14, description: "能够优化交互体验与页面性能" },
    learning: { level: 4, weight: 0.14, description: "持续学习前端生态与工程化方案" },
    stress: { level: 4, weight: 0.1, description: "适应需求频繁变化" },
    communication: { level: 4, weight: 0.15, description: "与产品/设计/后端高频协作" },
    experience: { level: 3, weight: 0.15, description: "具备模块级前端开发经验" },
  },
  {
    job_name: "测试工程师",
    category: "software",
    skills: { level: 4, weight: 0.22, description: "掌握功能、接口及自动化测试，保障交付质量" },
    certification: { level: 3, weight: 0.1, description: "具备测试岗位基础能力" },
    innovation: { level: 4, weight: 0.14, description: "可设计高质量测试策略与缺陷挖掘流程" },
    learning: { level: 4, weight: 0.14, description: "可快速理解业务并学习脚本化测试" },
    stress: { level: 4, weight: 0.1, description: "可承受版本发布与质量门禁压力" },
    communication: { level: 4, weight: 0.15, description: "与研发团队紧密沟通推进缺陷闭环" },
    experience: { level: 3, weight: 0.15, description: "具备测试执行与缺陷管理经验" },
  },
  {
    job_name: "实施工程师",
    category: "implementation",
    skills: { level: 4, weight: 0.22, description: "熟悉系统部署、环境配置与现场实施流程" },
    certification: { level: 3, weight: 0.1, description: "具备实施相关技术背景" },
    innovation: { level: 3, weight: 0.14, description: "可在客户场景中优化实施方案" },
    learning: { level: 4, weight: 0.14, description: "快速掌握业务系统与行业知识" },
    stress: { level: 4, weight: 0.1, description: "适应客户现场交付压力" },
    communication: { level: 5, weight: 0.15, description: "客户沟通与协同能力要求高" },
    experience: { level: 4, weight: 0.15, description: "具备部署与问题处理经验" },
  },
  {
    job_name: "技术支持工程师",
    category: "implementation",
    skills: { level: 4, weight: 0.22, description: "熟悉故障排查、日志分析与线上问题处理" },
    certification: { level: 3, weight: 0.1, description: "具备技术支持岗位基础要求" },
    innovation: { level: 3, weight: 0.14, description: "可沉淀问题模式并优化支持流程" },
    learning: { level: 4, weight: 0.14, description: "快速定位并学习复杂问题场景" },
    stress: { level: 4, weight: 0.1, description: "适应7x24响应与突发故障压力" },
    communication: { level: 5, weight: 0.15, description: "高频客户沟通与跨团队协作" },
    experience: { level: 4, weight: 0.15, description: "具备线上故障闭环处理经验" },
  },
  {
    job_name: "销售运营专员",
    category: "operation",
    skills: { level: 3, weight: 0.22, description: "掌握CRM操作与销售流程分析" },
    certification: { level: 2, weight: 0.1, description: "证书非强制，偏业务结果导向" },
    innovation: { level: 3, weight: 0.14, description: "可优化运营流程与协作机制" },
    learning: { level: 4, weight: 0.14, description: "快速理解业务逻辑与指标体系" },
    stress: { level: 4, weight: 0.1, description: "承受目标与指标压力" },
    communication: { level: 5, weight: 0.15, description: "跨部门协作沟通能力要求高" },
    experience: { level: 3, weight: 0.15, description: "具备运营执行经验" },
  },
  {
    job_name: "招聘专员",
    category: "operation",
    skills: { level: 3, weight: 0.22, description: "掌握招聘渠道管理与岗位画像沟通" },
    certification: { level: 2, weight: 0.1, description: "证书要求较低，综合素质优先" },
    innovation: { level: 3, weight: 0.14, description: "可优化招聘流程与候选人匹配策略" },
    learning: { level: 4, weight: 0.14, description: "快速理解用人部门需求" },
    stress: { level: 4, weight: 0.1, description: "承受招聘周期与目标压力" },
    communication: { level: 5, weight: 0.15, description: "高频沟通候选人与业务部门" },
    experience: { level: 3, weight: 0.15, description: "具备招聘执行与协同经验" },
  },
  {
    job_name: "储备干部/管培生",
    category: "operation",
    skills: { level: 3, weight: 0.2, description: "具备跨岗位轮岗与综合业务理解能力" },
    certification: { level: 2, weight: 0.1, description: "证书要求一般" },
    innovation: { level: 4, weight: 0.14, description: "可参与管理创新项目" },
    learning: { level: 5, weight: 0.16, description: "学习力强，适应多部门轮岗" },
    stress: { level: 4, weight: 0.1, description: "适应轮岗与结果压力" },
    communication: { level: 4, weight: 0.15, description: "跨部门沟通与协作能力良好" },
    experience: { level: 2, weight: 0.15, description: "经验要求相对宽松，偏潜力导向" },
  },
  {
    job_name: "项目经理",
    category: "product",
    skills: { level: 4, weight: 0.2, description: "精通项目管理方法论，承担交付成败责任" },
    certification: { level: 4, weight: 0.12, description: "PMP等项目管理证书加分明显" },
    innovation: { level: 4, weight: 0.14, description: "可优化项目流程与资源配置" },
    learning: { level: 4, weight: 0.12, description: "持续学习管理实践与行业方法" },
    stress: { level: 5, weight: 0.12, description: "抗压要求高，需要平衡时间成本范围" },
    communication: { level: 5, weight: 0.16, description: "强沟通与跨团队协调能力" },
    experience: { level: 5, weight: 0.14, description: "需要较深项目经验积累" },
  },
  {
    job_name: "科研人员",
    category: "research",
    skills: { level: 5, weight: 0.2, description: "具备深厚理论与研究方法能力" },
    certification: { level: 4, weight: 0.1, description: "高学历与研究背景要求较高" },
    innovation: { level: 5, weight: 0.2, description: "创新能力要求最高" },
    learning: { level: 5, weight: 0.15, description: "持续跟进前沿理论与技术" },
    stress: { level: 4, weight: 0.1, description: "可适应长期科研任务压力" },
    communication: { level: 3, weight: 0.1, description: "强调研究独立性与必要协作" },
    experience: { level: 5, weight: 0.15, description: "需要科研项目与成果积累" },
  },
];
